### ISSUE TITLE
Fixed computer

### ISSUE THREAD

**Issue by AlexanderJohnRobertson** [AlexanderJohnRobertson/Dissertation-Smart-Home-Weather-Dashboard#6]
I have fixed my laptop, reinstalled all software and restored all files from OneDrive (took a while as there was over 1TB of files).  I have now deleted and intstalled a new Python virtual environment .venv as a new version of Python was installed and everything is working again.  I plan to resume working on it this Sunday 27th October.

**Comment by kakiac** [comment]
This is fantastic @AlexanderJohnRobertson - well done for all the hard work and for bouncing back so quickly. We look forward to hearing more about the next steps in this project on Friday!
